//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandRegistrationUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlockMaster()
        {
            this.UsersDatas = new HashSet<UsersData>();
        }
    
        public int BlockID { get; set; }
        public string BlockName { get; set; }
        public int RevenueVillageId { get; set; }
    
        public virtual RevenueVillageMaster RevenueVillageMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersData> UsersDatas { get; set; }
    }
}
