//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandRegistrationUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RevenueVillageMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RevenueVillageMaster()
        {
            this.BlockMasters = new HashSet<BlockMaster>();
            this.WardMasters = new HashSet<WardMaster>();
            this.UsersDatas = new HashSet<UsersData>();
        }
    
        public int Id { get; set; }
        public string RevenueVillageName { get; set; }
        public int TalukID { get; set; }
        public bool IsWard { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockMaster> BlockMasters { get; set; }
        public virtual TalukMaster TalukMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WardMaster> WardMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersData> UsersDatas { get; set; }
    }
}
