//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandRegistrationUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TalukMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TalukMaster()
        {
            this.RevenueVillageMasters = new HashSet<RevenueVillageMaster>();
            this.UsersDatas = new HashSet<UsersData>();
        }
    
        public int TalukID { get; set; }
        public string TalukName { get; set; }
        public byte RegionID { get; set; }
    
        public virtual RegionMaster RegionMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RevenueVillageMaster> RevenueVillageMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersData> UsersDatas { get; set; }
    }
}
