//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LandRegistrationUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersData()
        {
            this.UserImages = new HashSet<UserImage>();
        }
    
        public int ID { get; set; }
        public byte RegionID { get; set; }
        public int TalukID { get; set; }
        public Nullable<int> WardID { get; set; }
        public Nullable<int> BlockID { get; set; }
        public int RevenueVillageID { get; set; }
        public string TSNo { get; set; }
        public string SubDivisionNo { get; set; }
        public string RSNo { get; set; }
        public string PattaNo { get; set; }
        public string OwnerName { get; set; }
        public string TenantName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public string PreviousOwnerAddLine1 { get; set; }
        public string PreviousOwnerAddLine2 { get; set; }
        public string PreviousOwnerAddLine3 { get; set; }
        public string Remarks { get; set; }
        public string Location { get; set; }
        public string Email { get; set; }
    
        public virtual BlockMaster BlockMaster { get; set; }
        public virtual RegionMaster RegionMaster { get; set; }
        public virtual RevenueVillageMaster RevenueVillageMaster { get; set; }
        public virtual TalukMaster TalukMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserImage> UserImages { get; set; }
    }
}
